name: .NET Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Build and Pack
        run: dotnet build --configuration Release
      - name: Publish to GitHub Packages
        run: dotnet nuget push "src/FluentAvalonia/bin/Release/*.nupkg" --api-key ${{secrets.NUGET_PACKAGE_TOKEN}} --source https://nuget.pkg.github.com/brokiem/index.json
